name: bookmyshow_tracker
description: This app notifies you when ticket sales for a movie begin on bookmyshow.com.

publish_to: "none"

version: 0.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  equatable: ^2.0.5
  workmanager: ^0.5.1
  intl: ^0.17.0
  url_launcher: ^6.1.6
  shared_preferences: ^2.0.15
  awesome_notifications: ^0.7.4+1
  flutter_bloc: ^8.1.1
  receive_sharing_intent: ^1.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.15

flutter:
  uses-material-design: true

# flutter_launcher_icons config
flutter_icons:
  android: true
  image_path: "assets/icons/bookmyshow-tracker-icon.png"

# flutter_native_splash config
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#E7394D"
  image: "assets/images/bookmyshow-tracker-splash-image-light.png"
  image_dark: "assets/images/bookmyshow-tracker-splash-image-dark.png"
  android_12:
    color: "#FFFFFF"
    color_dark: "#E7394D"
    image: "assets/images/bookmyshow-tracker-splash-image-light.png"
    image_dark: "assets/images/bookmyshow-tracker-splash-image-dark.png"
